### ISSUE TITLE
Upgrade from 9.1.2 to 10.0 fails..

### ISSUE THREAD

**Issue by brunis** [getsentry/self-hosted#1227]
### Version

9.1.2

### Steps to Reproduce

1. follow your upgrade guide. ( SENTRY_IMAGE=getsentry/sentry:10 ./install.sh )

### Expected Result

Expected it to work. 

### Actual Result

Building snuba-cleanup
Sending build context to Docker daemon  3.584kB
Step 1/5 : ARG BASE_IMAGE
Step 2/5 : FROM ${BASE_IMAGE}
 ---> 02e5b2c1f642
Step 3/5 : RUN apt-get update && apt-get install -y --no-install-recommends cron &&     rm -r /var/lib/apt/lists/*
 ---> Running in ed8b289d0769
Err:1 http://security.debian.org/debian-security bullseye-security InRelease
  Temporary failure resolving 'security.debian.org'
Err:2 http://deb.debian.org/debian bullseye InRelease
  Temporary failure resolving 'deb.debian.org'
Err:3 http://deb.debian.org/debian bullseye-updates InRelease
  Temporary failure resolving 'deb.debian.org'
Reading package lists...
W: Failed to fetch http://deb.debian.org/debian/dists/bullseye/InRelease  Temporary failure resolving 'deb.debian.org'
W: Failed to fetch http://security.debian.org/debian-security/dists/bullseye-security/InRelease  Temporary failure resolving 'security.debian.org'
W: Failed to fetch http://deb.debian.org/debian/dists/bullseye-updates/InRelease  Temporary failure resolving 'deb.debian.org'
W: Some index files failed to download. They have been ignored, or old ones used instead.
Reading package lists...
Building dependency tree...
Reading state information...
E: Unable to locate package cron
Removing intermediate container ed8b289d0769
The command '/bin/sh -c apt-get update && apt-get install -y --no-install-recommends cron &&     rm -r /var/lib/apt/lists/*' returned a non-zero code: 100
Service 'snuba-cleanup' failed to build : Build failed
An error occurred, caught SIGERR on line 4
Cleaning up...

**Comment by aminvakil** [comment]
Have you tried changing your DNS servers and running again?

**Comment by brunis** [comment]
> Have you tried changing your DNS servers and running again?

I have no issues resolving deb.debian.org from the host, i'm guessing it's the "snuba-clean" temp image that tries to update and fails..

**Comment by brunis** [comment]
I'm migrating from 9.1.2 so there is no pre-existing snuba, so i'm not sure why i need a cleanup, maybe i could skip this step without issues?

**Comment by aminvakil** [comment]
> > Have you tried changing your DNS servers and running again?
> 
> I have no issues resolving deb.debian.org from the host, i'm guessing it's the "snuba-clean" temp image that tries to update and fails..

Then maybe this was a temporary failure and it will pass if you run it again.

> I'm migrating from 9.1.2 so there is no pre-existing snuba, so i'm not sure why i need a cleanup, maybe i could skip this step without issues?

Not being able to resolve domains from containers is something which will make in next steps too, I would fix this step rather than skip it.

**Comment by brunis** [comment]
> > > Have you tried changing your DNS servers and running again?
> > 
> > 
> > I have no issues resolving deb.debian.org from the host, i'm guessing it's the "snuba-clean" temp image that tries to update and fails..
> 
> Then maybe this was a temporary failure and it will pass if you run it again.
> 
> > I'm migrating from 9.1.2 so there is no pre-existing snuba, so i'm not sure why i need a cleanup, maybe i could skip this step without issues?
> 
> Not being able to resolve domains from containers is something which will make in next steps too, I would fix this step rather than skip it.

I'm all for that, but how do i fix snuba-cleanup container to be able to access the internet? ..and why isn't the image just updated with needed packages instead of calling deb.debian.org when it isn't set up for it?  .. i think *that* should be fixed..

**Comment by aminvakil** [comment]
Does this work? `docker run --rm debian apt update`

**Comment by brunis** [comment]
> Does this work? `docker run --rm debian apt update`

No, exact same issue

**Comment by aminvakil** [comment]
> > Does this work? `docker run --rm debian apt update`
> 
> No, exact same issue

So this is definitely not related to sentry...

Please fix your environment and whenever official debian worked, try again with sentry.

**Comment by brunis** [comment]
> > > Does this work? `docker run --rm debian apt update`
> > 
> > 
> > No, exact same issue
> 
> So this is definitely not related to sentry...
> 
> Please fix your environment and whenever official debian worked, try again with sentry.

You are perfectly right, somehow i have internet access, but no docker apps had without an extra nameserver 8.8.8.8 (eg).
Thanks.

**Comment by aminvakil** [comment]
Glad that it's fixed now!

**Comment by brunis** [comment]
> Glad that it's fixed now!

Well, it's not fixed, it just doesn't get stuck with 'apt updates' in containers anymore. After every container is created with 'docker-compose up' (they all green-light ... done) i get this:
ERROR: for relay  Container "60f6f0106686" is unhealthy.
ERROR: Encountered errors while bringing up the project.

How do i figure out what goes wrong in that particular container?

**Comment by aminvakil** [comment]
@brunis Try to install again in a clean state (using `reset.sh` or manually), then paste errors of `install.sh`.

**Comment by chadwhitacre** [comment]
Ftr: #1235.
