### ISSUE TITLE
get() returned more than one UserOption -- it returned 2!

### ISSUE THREAD

**Issue by BaxAndrei** [getsentry/self-hosted#1295]
### Version

22.1.0

### Steps to Reproduce

1. Go to settings/account/details/
2. enter desired timezone

### Expected Result

Update timezone

### Actual Result

![image](https://user-images.githubusercontent.com/12484505/152444801-31fac7c9-a5ac-47a2-83dd-af0170c9b8ed.png)
![image](https://user-images.githubusercontent.com/12484505/152444843-1b23f66b-4d22-4445-8aa8-e99b0d17d141.png)

**Comment by chadwhitacre** [comment]
@BaxAndrei How did you end up with two `UserOption`s? 🤔 Did you upgrade recently? When did this start happening?

Is there a traceback with the error you can see where it's coming from and inspect the code there? From there you should be able to inspect your database and maybe the details of the useroptions will provide a clue?

**Comment by BaxAndrei** [comment]
This is a new installation, we have not performed any upgrade procedures. Regarding the question, I really don't know how my account came to have 2 UserOptions objects

If that doesn't work, how can I get more useful logs? Or is there a way to remove the extra object or set the timezone manually?

![image](https://user-images.githubusercontent.com/12484505/152447945-baede3f2-95ef-4c03-bca7-e8ad75ceae03.png)

**Comment by chadwhitacre** [comment]
Weird, like _new_ new? If you install again from scratch can you repro? Can you repro with an older version?

Is there anything else besides setting the timezone that fails with his error? UserOption seems more generic than just timezone, I would expect someone else to have run into this if it were a general bug.

**Comment by chadwhitacre** [comment]
> is there a way to remove the extra object

You could try it with a SQL `DELETE`, I guess, though it'd be better to find the root cause and address it.

**Comment by BaxAndrei** [comment]
I tried to use the main account (administrator created during installation) and delete the account permanently, but it gives me the error that I do not have permission to do so. It's brand new, I installed it a few days ago. The only thing I can't update is the timezone, otherwise everything is ok. I don't have this problem on the administrator account.

**Comment by BaxAndrei** [comment]
> > is there a way to remove the extra object
> 
> You could try it with a SQL `DELETE`, I guess, though it'd be better to find the root cause and address it.

That would be a temporary solution, too, and then it remains to be seen if it will happen again in the future, but I don't know which docker container to go into or how to delete that entry.

**Comment by chadwhitacre** [comment]
Hrm. Okay, lemme see if I can repro this, hopefully tomorrow ...

(Unless someone else can try first? 😀)

**Comment by aminvakil** [comment]
@BaxAndrei For future reference, has this been resolved with a clean installation as you have mentioned in https://github.com/getsentry/self-hosted/issues/1310#issuecomment-1032304975 ?

**Comment by BaxAndrei** [comment]
> @BaxAndrei For future reference, has this been resolved with a clean installation as you have mentioned in [#1310 (comment)](https://github.com/getsentry/self-hosted/issues/1310#issuecomment-1032304975) ?

Yes, unfortunately this is the only way I managed to solve it and I still don't know what was the cause of this problem, but I hope it doesn't happen again.
