### ISSUE TITLE
Deleting a replay record leads to snuba-replays-consumer crash

### ISSUE THREAD

**Issue by tm1000** [getsentry/self-hosted#2055]
### Self-Hosted Version

23.3.1

### CPU Architecture

x86_64

### Docker Version

23.0.1

### Docker Compose Version

2.16.0

### Steps to Reproduce

Set env:
`SENTRY_IMAGE=getsentry/sentry:83a82aa`

Enable replay and go to a replay event in the ui and click delete

### Expected Result

Replay record should be deleted.

### Actual Result

After clicking on the delete button, the container "snuba-replays-consumer" keeps crashing

Here are the logs of the containers:

```
2023-03-30 08:35:58,982 Processor terminated
Traceback (most recent call last):
  File "/usr/local/bin/snuba", line 33, in <module>
    sys.exit(load_entry_point('snuba', 'console_scripts', 'snuba')())
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/usr/src/snuba/snuba/cli/consumer.py", line 203, in consumer
    consumer.run()
  File "/usr/local/lib/python3.8/site-packages/arroyo/processing/processor.py", line 181, in run
    self._run_once()
  File "/usr/local/lib/python3.8/site-packages/arroyo/processing/processor.py", line 221, in _run_once
    self.__processing_strategy.poll()
  File "/usr/local/lib/python3.8/site-packages/arroyo/processing/strategies/dead_letter_queue/dead_letter_queue.py", line 39, in poll
    self.__next_step.poll()
  File "/usr/local/lib/python3.8/site-packages/arroyo/processing/strategies/run_task.py", line 71, in poll
    self.__next_step.poll()
  File "/usr/local/lib/python3.8/site-packages/arroyo/processing/strategies/reduce.py", line 149, in poll
    self.__next_step.poll()
  File "/usr/local/lib/python3.8/site-packages/arroyo/processing/strategies/run_task.py", line 151, in poll
    result = future.result()
  File "/usr/local/lib/python3.8/concurrent/futures/_base.py", line 437, in result
    return self.__get_result()
  File "/usr/local/lib/python3.8/concurrent/futures/_base.py", line 389, in __get_result
    raise self._exception
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/src/snuba/snuba/consumers/strategy_factory.py", line 120, in flush_batch
    message.payload.close()
  File "/usr/src/snuba/snuba/consumers/consumer.py", line 296, in close
    self.__insert_batch_writer.close()
  File "/usr/src/snuba/snuba/consumers/consumer.py", line 135, in close
    self.__writer.write(
  File "/usr/src/snuba/snuba/clickhouse/http.py", line 328, in write
    batch.join()
  File "/usr/src/snuba/snuba/clickhouse/http.py", line 266, in join
    raise ClickhouseWriterError(message, code=code, row=row)
snuba.clickhouse.errors.ClickhouseWriterError: Cannot parse JSON string: expected opening quote: (while read the value of key sdk_name): (at row 1)
```

**Comment by tm1000** [comment]
This a continuation of #2042 just with `sdk_name` now...

@JoshFerge

**Comment by tm1000** [comment]
This is probably actually related to https://github.com/getsentry/snuba/pull/3908

**Comment by JoshFerge** [comment]
thanks @tm1000 -- yes i think https://github.com/getsentry/snuba/pull/3908 should fix this.

**Comment by tm1000** [comment]
@JoshFerge so I got that snuba up. It still doesnt delete the replay BUT it does not crash any containers. So I think thats a "win" in my book.

**Comment by hubertdeng123** [comment]
thanks for reporting @tm1000, are there any errors when trying to delete the replay now?

**Comment by tm1000** [comment]
@hubertdeng123 Which container would I look at for this? The snuba container doesnt have any errors itself. I also dont see anything in the "interal" project.

When I do try to delete now I get a toast notification that says "Failed to delete replay"
