### ISSUE TITLE
Sentry self-hosted backup restoration issue

### ISSUE THREAD

**Issue by atalakey4work** [getsentry/self-hosted#2468]
### Self-Hosted Version

23.9.1

### CPU Architecture

x86_64

### Docker Version

24.0.5

### Docker Compose Version

2.20.2

### Steps to Reproduce

1. Take a backup: sentry export global /etc/sentry/backup.json
2. Restore backup: sentry import global /etc/sentry/backup.json

### Expected Result

Backup restoration complete successfully

### Actual Result

Traceback (most recent call last):
  File "/usr/local/bin/sentry", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/site-packages/sentry/runner/__init__.py", line 193, in main
    func(**kwargs)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/sentry/runner/decorators.py", line 29, in inner
    return ctx.invoke(f, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/sentry/runner/commands/backup.py", line 120, in import_global
    import_in_global_scope(
  File "/usr/local/lib/python3.8/site-packages/sentry/backup/imports.py", line 246, in import_in_global_scope
    return _import(src, ImportScope.Global, flags=flags, printer=printer)
  File "/usr/local/lib/python3.8/site-packages/sentry/backup/imports.py", line 143, in _import
    written = o.write_relocation_import(scope, flags)
  File "/usr/local/lib/python3.8/site-packages/sentry/models/useremail.py", line 109, in write_relocation_import
    useremail = self.__class__.objects.get(user=self.user, email=self.email)
  File "/usr/local/lib/python3.8/site-packages/sentry/db/models/manager/base.py", line 260, in get
    return super().get(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/db/models/query.py", line 435, in get
    raise self.model.DoesNotExist(
sentry.models.useremail.DoesNotExist: UserEmail matching query does not exist.
Sentry is attempting to send 2 pending events
Waiting up to 2 seconds
Press Ctrl-C to quit
command terminated with exit code 1

**Comment by atalakey4work** [comment]
Yes I am

**Comment by atalakey4work** [comment]
I did the action requested by restoring to a clean database and using the --skip-user-creation but still getting the same error. Also note that I need all the data; thus, using the "global" option.

**Comment by azaslavsky** [comment]
Are you able to connect to the postgres instance directly? Can you tell me how many entries you have in the auth_user and sentry_userip tables? My suspicion is that you have only admin@localhost in your auth_user table?

**Comment by atalakey4work** [comment]
Yes,  am able to to connect to the postgres instance directly. Both tables are empty.

sentry=# select * from auth_user;
 id | password | last_login | username | first_name | email | is_staff | is_active | is_superuser | is_managed | is_sentry_app | is_password_expired | last_password_change | flags | session_nonce | date
_joined | last_active | avatar_type | avatar_url | is_unclaimed 
----+----------+------------+----------+------------+-------+----------+-----------+--------------+------------+---------------+---------------------+----------------------+-------+---------------+-----
--------+-------------+-------------+------------+--------------
(0 rows)

sentry=# select * from sentry_userip;
 id | ip_address | country_code | region_code | first_seen | last_seen | user_id 
----+------------+--------------+-------------+------------+-----------+---------
(0 rows)

**Comment by azaslavsky** [comment]
Ok, I believe that this is a bug. I'm working on a fix, and hope to have one out by the end of next week.

**Comment by WilenChen** [comment]
same problem, 23.9.1

**Comment by amrfawzy-hostaway** [comment]
Same error, the restore script returns the following o/p:
```
Running hooks in /etc/ca-certificates/update.d...
done.
/usr/local/lib/python3.8/site-packages/memcache.py:1303: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if key is '':
/usr/local/lib/python3.8/site-packages/memcache.py:1304: SyntaxWarning: "is" with a literal. Did you mean "=="?
  if key_extra_len is 0:
Traceback (most recent call last):
  File "/usr/local/bin/sentry", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/site-packages/sentry/runner/__init__.py", line 195, in main
    func(**kwargs)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/sentry/runner/decorators.py", line 29, in inner
    return ctx.invoke(f, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/sentry/runner/commands/backup.py", line 239, in import_global
    import_in_global_scope(
  File "/usr/local/lib/python3.8/site-packages/sentry/backup/imports.py", line 340, in import_in_global_scope
    return _import(
  File "/usr/local/lib/python3.8/site-packages/sentry/backup/imports.py", line 211, in _import
    do_write()
  File "/usr/local/lib/python3.8/site-packages/sentry/backup/imports.py", line 191, in do_write
    written = o.write_relocation_import(scope, flags)
  File "/usr/local/lib/python3.8/site-packages/sentry/models/userip.py", line 82, in write_relocation_import
    (userip, created) = self.__class__.objects.get_or_create(
  File "/usr/local/lib/python3.8/site-packages/sentry/silo/base.py", line 160, in override
    return original_method(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/sentry/silo/base.py", line 160, in override
    return original_method(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/django/db/models/query.py", line 581, in get_or_create
    return self.get(**kwargs), False
  File "/usr/local/lib/python3.8/site-packages/django/db/models/query.py", line 439, in get
    raise self.model.MultipleObjectsReturned(
sentry.models.userip.MultipleObjectsReturned: get() returned more than one UserIP -- it returned 2!
Error in scripts/_lib.sh:69.
'$dc run --rm -T web import global /etc/sentry/backup.json' exited with status 1
-> ./scripts/restore.sh:main:4
--> scripts/_lib.sh:restore:69

Cleaning up...
```
both instances are : `23.10.0`
I tried to restore to an empty database (didn't create a user during the installation).

**Comment by atalakey4work** [comment]
@azaslavsky any luck on this?

**Comment by azaslavsky** [comment]
I *think* I have a fix up, but I want to double-check: can you post a (scrubbed! Don't reveal real IPs!) version of all of the `"model": "sentry.userip"` entries in one of your export JSONs that causes this bug? I want to double check that my solution fixes your specific case, and not a related issue.

**Comment by azaslavsky** [comment]
I've put up https://github.com/getsentry/sentry/pull/59732 for review, which should fix this. I'll post again once this rolls through.

**Comment by atalakey4work** [comment]
Attached version of all of the "model": "sentry.userip" entries (scrubbed).
[Uploading backup.json…]()

**Comment by azaslavsky** [comment]
That link doesn't appear to work? You could also just paste it in a code block like so, if its not very big:
```
[...]
```

**Comment by azaslavsky** [comment]
The PR landed, but want to make sure your test case is covered before marking this closed.

**Comment by atalakey4work** [comment]
It is large. Attaching again.

[backup.json](https://github.com/getsentry/self-hosted/files/13325016/backup.json)

**Comment by azaslavsky** [comment]
Very odd that you have this output, since the DB has a constraint to ensure that every user:ip_address combination is unique. In any case, I believe the fix I pushed onto master should work for this - can you try to pull from head and see if the script works now?

**Comment by Hugo-Persson** [comment]
I have pulled from master but still get the following error:

```
RpcImportError(
	kind: Unknown,
	on: InstanceID(model: 'sentry.useremail'),
	reason: Unknown internal error occurred: UserEmail matching query does not exist.
)
```

**Comment by azaslavsky** [comment]
Same request as above - can you post a sanitized version of the `sentry.useremail` entries in your backup.json? Also, which version of self-hosted did you use to generate your backup @Hugo-Persson ? Actually, would you mind creating a new issue for your error, since I'm not sure it is directly related to this one.

**Comment by Hugo-Persson** [comment]
@azaslavsky 
I created this issue https://github.com/getsentry/self-hosted/issues/2571#event-10969999898, but it was closed because this similar. 

I used version 23.10.1. How should I create sanitized version?

**Comment by azaslavsky** [comment]
@Hugo-Persson I've re-opened your issue. Let's continue the discussion there.

**Comment by webard** [comment]
There is problem with Alert Rules too:
```
RpcImportError(
    kind: Unknown,
    on: InstanceID(model: 'sentry.alertrule'),
    reason: Unknown internal error occurred: Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/sentry/services/hybrid_cloud/import_export/impl.py", line 220, in import_by_model
    written = model_instance.write_relocation_import(
  File "/usr/local/lib/python3.10/site-packages/sentry/db/models/base.py", line 243, in write_relocation_import
    self.save(force_insert=True)
  File "/usr/local/lib/python3.10/site-packages/sentry/incidents/models.py", line 468, in save
    self._validate_actor()
  File "/usr/local/lib/python3.10/site-packages/sentry/incidents/models.py", line 465, in _validate_actor
    raise ValueError("AlertRule with owner requires either team_id or user_id")
ValueError: AlertRule with owner requires either team_id or user_id

)


RpcImportError(
    kind: Unknown,
    on: InstanceID(model: 'sentry.alertrule'),
    reason: Unknown internal error occurred: Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/sentry/services/hybrid_cloud/import_export/impl.py", line 220, in import_by_model
    written = model_instance.write_relocation_import(
  File "/usr/local/lib/python3.10/site-packages/sentry/db/models/base.py", line 243, in write_relocation_import
    self.save(force_insert=True)
  File "/usr/local/lib/python3.10/site-packages/sentry/incidents/models.py", line 468, in save
    self._validate_actor()
  File "/usr/local/lib/python3.10/site-packages/sentry/incidents/models.py", line 465, in _validate_actor
    raise ValueError("AlertRule with owner requires either team_id or user_id")
ValueError: AlertRule with owner requires either team_id or user_id

)
Traceback (most recent call last):
  File "/usr/local/bin/sentry", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.10/site-packages/sentry/runner/__init__.py", line 195, in main
    func(**kwargs)
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/click/decorators.py", line 33, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/sentry/runner/decorators.py", line 29, in inner
    return ctx.invoke(f, *args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/sentry/runner/commands/backup.py", line 722, in import_global
    import_in_global_scope(
  File "/usr/local/lib/python3.10/site-packages/sentry/backup/imports.py", line 479, in import_in_global_scope
    return _import(
  File "/usr/local/lib/python3.10/site-packages/sentry/backup/imports.py", line 362, in _import
    do_writes(pk_map)
  File "/usr/local/lib/python3.10/site-packages/sentry/backup/imports.py", line 324, in do_writes
    do_write(import_write_context, pk_map, model_name, json_data)
  File "/usr/local/lib/python3.10/site-packages/sentry/backup/imports.py", line 264, in do_write
    raise ImportingError(result)
sentry.backup.imports.ImportingError: is_err=True kind='Unknown' on=InstanceID(model='sentry.alertrule', ordinal=None) left_pk=None right_pk=None reason='Unknown internal error occurred: Traceback (most recent call last):\n  File "/usr/local/lib/python3.10/site-packages/sentry/services/hybrid_cloud/import_export/impl.py", line 220, in import_by_model\n    written = model_instance.write_relocation_import(\n  File "/usr/local/lib/python3.10/site-packages/sentry/db/models/base.py", line 243, in write_relocation_import\n    self.save(force_insert=True)\n  File "/usr/local/lib/python3.10/site-packages/sentry/incidents/models.py", line 468, in save\n    self._validate_actor()\n  File "/usr/local/lib/python3.10/site-packages/sentry/incidents/models.py", line 465, in _validate_actor\n    raise ValueError("AlertRule with owner requires either team_id or user_id")\nValueError: AlertRule with owner requires either team_id or user_id\n'
Error in scripts/_lib.sh:69.
'$dc run --rm -T web import global /etc/sentry/backup.json' exited with status 1
-> ./scripts/restore.sh:main:4
--> scripts/_lib.sh:restore:69
```

my backup.json contains this entry:
```
    {
        "model": "sentry.alertrule",
        "pk": 1,
        "fields":
        {
            "organization": 1,
            "snuba_query": 1,
            "owner": 3,
            "user_id": null,
            "team": null,
            "name": "Crash free sessions on production",
            "status": 0,
            "include_all_projects": false,
            "threshold_type": 1,
            "resolve_threshold": 90.0,
            "threshold_period": 1,
            "comparison_delta": null,
            "date_modified": "2023-09-22T09:20:08.368Z",
            "date_added": "2023-09-22T09:19:44.753Z"
        }
    },
```

and probably nulled user_id and team_id causes problem.

**Comment by webard** [comment]
Next problem is different project ids on original sentry vs backup.json, for example one of my project has id=4, in backup.json and, as a result of restore, on restored server has id=7.

**Comment by azaslavsky** [comment]
The AlertRule bug has been [fixed](https://github.com/getsentry/sentry/pull/62526), and will be out in the next release (probably going out today or tomorrow).

The project id issue is discussed here: https://github.com/getsentry/self-hosted/issues/2678.

**Comment by azaslavsky** [comment]
24.1.0 is out, which has the AlertRule bug fix included.
