### ISSUE TITLE
After upgrading our sentry to 24.9.0 we are facing sentry.auth.system: Trying to use `SystemToken` from non-internal IP

### ISSUE THREAD

**Issue by balaG4046** [getsentry/self-hosted#3353]
### Environment

self-hosted (https://develop.sentry.dev/self-hosted/)

### Steps to Reproduce

Hi Team,

We have upgraded our sentry self hosted recently to 24.9.0, we are facing below issue intermittently, once after the restarting the container **sentry-self-hosted-web-1** sentry came up, 
Error logs 

15:06:20 [WARNING] django.request: Unauthorized: /api/0/projects/cds/evolio-masterdata-service/files/dsyms/ (status_code=401 request=<WSGIRequest: GET '/api/0/projects/cds/evolio-masterdata-service/files/dsyms/?debug_id=c80d19dc-4dc3-4765-9532-ea111a4c6061-e8be40ea'>)
15:06:20 [WARNING] django.request: Unauthorized: /api/0/projects/cds/evolio-masterdata-service/files/dsyms/ (status_code=401 request=<WSGIRequest: GET '/api/0/projects/cds/evolio-masterdata-service/files/dsyms/?debug_id=4702619c-5710-adc8-55f3-6ae683edbf5f-694b73fc'>)
15:06:20 [ERROR] sentry.auth.system: Trying to use `SystemToken` from non-internal IP
15:06:20 [ERROR] sentry.auth.system: Trying to use `SystemToken` from non-internal IP
15:06:20 [ERROR] sentry.auth.system: Trying to use `SystemToken` from non-internal IP
15:06:20 [ERROR] sentry.auth.system: Trying to use `SystemToken` from non-internal IP

Kindly help us with the solution to resolve the issue.

Thanks!

### Expected Result

it should work with any issue.

### Actual Result

Please find the error logs- 
-----------------------------------------------------------
15:06:20 [WARNING] django.request: Unauthorized: /api/0/projects/cds/evolio-masterdata-service/files/dsyms/ (status_code=401 request=<WSGIRequest: GET '/api/0/projects/cds/evolio-masterdata-service/files/dsyms/?debug_id=c80d19dc-4dc3-4765-9532-ea111a4c6061-e8be40ea'>)
15:06:20 [WARNING] django.request: Unauthorized: /api/0/projects/cds/evolio-masterdata-service/files/dsyms/ (status_code=401 request=<WSGIRequest: GET '/api/0/projects/cds/evolio-masterdata-service/files/dsyms/?debug_id=4702619c-5710-adc8-55f3-6ae683edbf5f-694b73fc'>)
15:06:20 [ERROR] sentry.auth.system: Trying to use `SystemToken` from non-internal IP
15:06:20 [ERROR] sentry.auth.system: Trying to use `SystemToken` from non-internal IP
15:06:20 [ERROR] sentry.auth.system: Trying to use `SystemToken` from non-internal IP
15:06:20 [ERROR] sentry.auth.system: Trying to use `SystemToken` from non-internal IP

### Product Area

Issues

### Version

24.9.0

**Comment by balaG4046** [comment]
hi team, any update here

**Comment by aldy505** [comment]
Did you modify your Docker network IP range to something that's not in the private IP ranges? See here: https://develop.sentry.dev/self-hosted/troubleshooting/#docker-network-conflicting-ip-address

The easiest solution is just restart your Docker engine. `sudo systemctl restart docker`

**Comment by balaG4046** [comment]
Hi @aldy505 
Thanks for your update, we have not modified any ip range, but this issue is coming after we moved to 24.9.0 version, however we are restarting the container to resolve the issue, it would be better if we can permanently fix the issue rather than restarting the container.

Thanks!

**Comment by aldy505** [comment]
Okay, another guess, do you happen to have these lines on your `sentry/sentry.conf.py` file?

https://github.com/getsentry/self-hosted/blob/bdf8d3ff918d92b04d10906f3869900ca41ec3bf/sentry/sentry.conf.example.py#L16-L42

**Comment by balaG4046** [comment]
yes we do have this line in our conf file @aldy505 today also we faced the same issue again, please help us with the solution. is this issue fixed in 24.10.0 ? ref(feedback): 401 for unauth'd POSTs to projectUserReports (https://github.com/getsentry/sentry/pull/79069) ?

**Comment by arussell** [comment]
I am also seeing this issue, `get_internal_network()` returns WAN IP. Hard coding internal Docker range with `INTERNAL_SYSTEM_IPS = ("172.16.0.0/12")` and rerunning `./install.sh` does not fix the issue, still see the error:

```
[ERROR] sentry.auth.system: Trying to use SystemToken from non-internal IP
```

**Comment by balaG4046** [comment]
Hi @aldy505 
Kindly help me with an update.

Thanks!

**Comment by aamarques** [comment]
The same is true here. I can't access `account/notifications` or `account/security`.

**Comment by balaG4046** [comment]
Hi @aldy505
Kindly help me with an update.

Thanks!

**Comment by aldy505** [comment]
Sorry, at this point I have no idea on how to fix this (and how to debug this).

**Comment by aamarques** [comment]
This has been working until 24.7.0, and suddenly, the problem is ours.
Someone somewhere removed a piece that works, and we cannot change the notify and security page.

**Comment by balaG4046** [comment]
@aldy505  can you forward this issue to anyone from your team to look it,

**Comment by aamarques** [comment]
@hubertdeng123 Did you see this issue ? Can you help us ?

**Comment by aldy505** [comment]
@bc-sentry Hello, can you help by transferring this to getsentry/sentry for triage? Thank you!

**Comment by bc-sentry** [comment]
@aldy505 Sentry internal won't be able to help with this.  We would have to know the IP address that is not being considered internal.  Unfortunately, there is no easy way for the developer to add a print statement to the code to show that IP address.  The IP addresses that are considered internal are listed in [server.py](https://github.com/getsentry/sentry/blob/master/src/sentry/conf/server.py#L142-L157).  Perhaps they could re-check their container IP ranges and see if anything looks odd.

**Comment by aamarques** [comment]
Here too. 
This happened from scratch, so something has been changed somewhere.

**Comment by aamarques** [comment]
After researching the Internet, I found this issue: https://github.com/getsentry/self-hosted/issues/2632.
My `sentry.conf.py` has a function to resolve the  `INTERNAL_SYSTEM_IPS = (get_internal_network(),)`, and this "solution" the guy seems to put the values by hand. (https://github.com/getsentry/self-hosted/issues/2632#issuecomment-1860400590).

1 - What is the correct behaviour: use function or add manually? 
2 - How can I check if the `sentry.conf.py` is running ok ?  Executing it in the container ?

**Comment by arussell** [comment]
@aamarques I tried this earlier in this thread, but it didn't seem to help:

> I am also seeing this issue under 24.10.0, `get_internal_network()` returns WAN IP. Hard coding internal Docker range with `INTERNAL_SYSTEM_IPS = ("172.16.0.0/12")` and rerunning `./install.sh` does not fix the issue, still see the error:
> 
> ```
> [ERROR] sentry.auth.system: Trying to use SystemToken from non-internal IP
> ```

**Comment by aamarques** [comment]
> [@aamarques](https://github.com/aamarques) I tried this earlier in this thread, but it didn't seem to help:
> 
> > I am also seeing this issue under 24.10.0, `get_internal_network()` returns WAN IP. Hard coding internal Docker range with `INTERNAL_SYSTEM_IPS = ("172.16.0.0/12")` and rerunning `./install.sh` does not fix the issue, still see the error:
> > ```
> > [ERROR] sentry.auth.system: Trying to use SystemToken from non-internal IP
> > ```

Sorry man. I can't understand how a thing that works, stop to work and nobody has an answer.

**Comment by bc-sentry** [comment]
@balaG4046 Sorry that we haven't been able to help you fix this.  As I was looking again at your initial post, it doesn't say exactly what the failure does or blocks you from doing.  You showed two HTTP 401's trying to access project dsym files and then the 4 errors Trying to use SystemToken from non-internal IP.  As a quick test, I just uploaded a dsym to a self-hosted project using the sentry-cli and it worked.  To help us diagnoses further, what is the actual problem caused by these errors in the log?  Thanks.

**Comment by aamarques** [comment]
Hey @bc-sentry this block these features: https://github.com/getsentry/self-hosted/issues/3420

**Comment by hubertdeng123** [comment]
Just to confirm, are all you folks using symbolicator?

The `INTERNAL_SYSTEM_IPS = (get_internal_network(),)` is a function we use as an attempt to automatically add a list of internal IPs for you. If that fails, you should manually add them. 

Here is the line of code that is throwing the error: https://github.com/getsentry/sentry/blob/master/src/sentry/auth/system.py#L51

**Comment by hubertdeng123** [comment]
Wondering if symbolicator for some reason is being treated as a non-internal IP

**Comment by balaG4046** [comment]
Hi @hubertdeng123 
Yes we are using symbolicator, i guess as you said symbolicator is being treated as non internal Ip, when we checked the symbolicator logs we found 401 unauthorized error - please refer the screenshot 

Kindly let us know how to fix this issue - need your help and suggestion
![Image](https://github.com/user-attachments/assets/0f477902-6577-4a68-ab17-5c12fcf05466)

**Comment by aamarques** [comment]
Hi @hubertdeng123 and @balaG4046 that the same here.

```
sentry-self-hosted-symbolicator-1               | 2024-11-25T10:09:47.637676325Z  WARN symbolicator_service::download::sentry: Sentry API returned status code 401 Unauthorized
sentry-self-hosted-symbolicator-1               | 2024-11-25T10:09:47.743927042Z  WARN symbolicator_service::download::sentry: Sentry API returned status code 401 Unauthorized
sentry-self-hosted-symbolicator-1               | 2024-11-25T10:09:52.223670594Z  WARN symbolicator_service::download::sentry: Sentry API returned status code 401 Unauthorized
sentry-self-hosted-symbolicator-1               | 2024-11-25T10:09:52.341258233Z  WARN symbolicator_service::download::sentry: Sentry API returned status code 401 Unauthorized
sentry-self-hosted-symbolicator-1               | 2024-11-25T10:09:52.445518454Z  WARN symbolicator_service::download::sentry: Sentry API returned status code 401 Unauthorized
sentry-self-hosted-symbolicator-1               | 2024-11-25T10:09:52.528391598Z  WARN symbolicator_service::download::sentry: Sentry API returned status code 401 Unauthorized
sentry-self-hosted-symbolicator-1               | 2024-11-25T10:09:52.636199742Z  WARN symbolicator_service::download::sentry: Sentry API returned status code 401 Unauthorized
sentry-self-hosted-symbolicator-1               | 2024-11-25T10:09:52.741299372Z  WARN symbolicator_service::download::sentry: Sentry API returned status code 401 Unauthorized
```

**Comment by balaG4046** [comment]
Hi @hubertdeng123 
Any update please.

Thanks!

**Comment by aamarques** [comment]
Morning, The workaround I did : https://forum.sentry.io/t/symbolicator-401-unauthorized-error/13878/5

I added the following and the external IP (XX.XX.XX.XX) that reaches the web. In my case, Sentry is internal, and all traffic comes from one IP.

Now I don't have that error. I'll try other ways also.
```
INTERNAL_SYSTEM_IPS = (
    "0.0.0.0/8",
    "10.0.0.0/8",
    "100.64.0.0/10",
    "127.0.0.0/8",
    "169.254.0.0/16",
    "172.16.0.0/12",
    "192.0.0.0/29",
    "192.0.2.0/24",
    "192.88.99.0/24",
    "192.168.0.0/16",
    "198.18.0.0/15",
    "198.51.100.0/24",
    "224.0.0.0/4",
    "240.0.0.0/4",
    "255.255.255.255/32",
   "XX.XX.XX.XX", 
)
```

BUT THE PAGES NOTIFICATION AND SECURITY STILL DON'T WORK.

**Comment by balaG4046** [comment]
> Morning, The workaround I did : https://forum.sentry.io/t/symbolicator-401-unauthorized-error/13878/5
> 
> I added the following and the external IP (XX.XX.XX.XX) that reaches the web. In my case, Sentry is internal, and all traffic comes from one IP.
> 
> Now I don't have that error. I'll try other ways also.
> 
> ```
> INTERNAL_SYSTEM_IPS = (
>     "0.0.0.0/8",
>     "10.0.0.0/8",
>     "100.64.0.0/10",
>     "127.0.0.0/8",
>     "169.254.0.0/16",
>     "172.16.0.0/12",
>     "192.0.0.0/29",
>     "192.0.2.0/24",
>     "192.88.99.0/24",
>     "192.168.0.0/16",
>     "198.18.0.0/15",
>     "198.51.100.0/24",
>     "224.0.0.0/4",
>     "240.0.0.0/4",
>     "255.255.255.255/32",
>    "XX.XX.XX.XX", 
> )
> ```
> 
> BUT THE PAGES NOTIFICATION AND SECURITY STILL DON'T WORK.

so you saying we need to update the above internal ip list mannulay in senty.conf.py file to resolve the issue ? 

now we have the below line in our sentry.conf.py 

def get_internal_network():
    import ctypes
    import fcntl
    import math
    import socket
    import struct

    iface = b"eth0"
    sockfd = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
    ifreq = struct.pack(b"16sH14s", iface, socket.AF_INET, b"\x00" * 14)

    try:
        ip = struct.unpack(
            b"!I", struct.unpack(b"16sH2x4s8x", fcntl.ioctl(sockfd, 0x8915, ifreq))[2]
        )[0]
        netmask = socket.ntohl(
            struct.unpack(b"16sH2xI8x", fcntl.ioctl(sockfd, 0x891B, ifreq))[2]
        )
    except IOError:
        return ()
    base = socket.inet_ntoa(struct.pack(b"!I", ip & netmask))
    netmask_bits = 32 - int(round(math.log(ctypes.c_uint32(~netmask).value + 1, 2), 1))
    return "{0:s}/{1:d}".format(base, netmask_bits)


INTERNAL_SYSTEM_IPS = (get_internal_network(),)
 
but now we need to add 
> INTERNAL_SYSTEM_IPS = (
>     "0.0.0.0/8",
>     "10.0.0.0/8",
>     "100.64.0.0/10",
>     "127.0.0.0/8",
>     "169.254.0.0/16",
>     "172.16.0.0/12",
>     "192.0.0.0/29",
>     "192.0.2.0/24",
>     "192.88.99.0/24",
>     "192.168.0.0/16",
>     "198.18.0.0/15",
>     "198.51.100.0/24",
>     "224.0.0.0/4",
>     "240.0.0.0/4",
>     "255.255.255.255/32",
>    "XX.XX.XX.XX", 
> )

**Comment by hubertdeng123** [comment]
> BUT THE PAGES NOTIFICATION AND SECURITY STILL DON'T WORK.

 @aamarques What error are you seeing now then?

**Comment by aamarques** [comment]
> > BUT THE PAGES NOTIFICATION AND SECURITY STILL DON'T WORK.
> 
> [@aamarques](https://github.com/aamarques) What error are you seeing now then?

When I click on `security`

![Image](https://github.com/user-attachments/assets/51130afe-681a-40b9-b76c-e69f8489aefb)



And when I click on `Notification`

![Image](https://github.com/user-attachments/assets/fd8b7a11-56f6-4a92-af34-657bd31f9094)

This run forever.

I have no 5xx or 4xx errors on log. I don't know where I can fix it.

Thanks

**Comment by aamarques** [comment]
> > Morning, The workaround I did : https://forum.sentry.io/t/symbolicator-401-unauthorized-error/13878/5
> > I added the following and the external IP (XX.XX.XX.XX) that reaches the web. In my case, Sentry is internal, and all traffic comes from one IP.
> > Now I don't have that error. I'll try other ways also.
> > ```
> > INTERNAL_SYSTEM_IPS = (
> >     "0.0.0.0/8",
> >     "10.0.0.0/8",
> >     "100.64.0.0/10",
> >     "127.0.0.0/8",
> >     "169.254.0.0/16",
> >     "172.16.0.0/12",
> >     "192.0.0.0/29",
> >     "192.0.2.0/24",
> >     "192.88.99.0/24",
> >     "192.168.0.0/16",
> >     "198.18.0.0/15",
> >     "198.51.100.0/24",
> >     "224.0.0.0/4",
> >     "240.0.0.0/4",
> >     "255.255.255.255/32",
> >    "XX.XX.XX.XX", 
> > )
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > BUT THE PAGES NOTIFICATION AND SECURITY STILL DON'T WORK.
> 
> so you saying we need to update the above internal ip list mannulay in senty.conf.py file to resolve the issue ?
> 
> now we have the below line in our sentry.conf.py
> 
> def get_internal_network(): import ctypes import fcntl import math import socket import struct
> 
> ```
> iface = b"eth0"
> sockfd = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
> ifreq = struct.pack(b"16sH14s", iface, socket.AF_INET, b"\x00" * 14)
> 
> try:
>     ip = struct.unpack(
>         b"!I", struct.unpack(b"16sH2x4s8x", fcntl.ioctl(sockfd, 0x8915, ifreq))[2]
>     )[0]
>     netmask = socket.ntohl(
>         struct.unpack(b"16sH2xI8x", fcntl.ioctl(sockfd, 0x891B, ifreq))[2]
>     )
> except IOError:
>     return ()
> base = socket.inet_ntoa(struct.pack(b"!I", ip & netmask))
> netmask_bits = 32 - int(round(math.log(ctypes.c_uint32(~netmask).value + 1, 2), 1))
> return "{0:s}/{1:d}".format(base, netmask_bits)
> ```
> 
> INTERNAL_SYSTEM_IPS = (get_internal_network(),)
> 
> but now we need to add
> 
> > INTERNAL_SYSTEM_IPS = (
> > "0.0.0.0/8",
> > "10.0.0.0/8",
> > "100.64.0.0/10",
> > "127.0.0.0/8",
> > "169.254.0.0/16",
> > "172.16.0.0/12",
> > "192.0.0.0/29",
> > "192.0.2.0/24",
> > "192.88.99.0/24",
> > "192.168.0.0/16",
> > "198.18.0.0/15",
> > "198.51.100.0/24",
> > "224.0.0.0/4",
> > "240.0.0.0/4",
> > "255.255.255.255/32",
> > "XX.XX.XX.XX",
> > )

First, I'm not saying anything you should or must do. I just up what work for me.|
You can find it here https://forum.sentry.io/t/symbolicator-401-unauthorized-error/13878/5

I don't know if it's the correct solution, and I don't care. I want my Sentry working, and my Company chooses to use open-source Software, so sometimes, we need to help the guys behind the scenes.

USE AT YOUR  RISK

**Comment by bc-sentry** [comment]
@aamarques Could you please capture a HAR file containing the network traffic from the browser?  It seems the client side would have received an error to show "There was an error loading data".  If you are using Chrome, on the Developer Tools -> Network traffic tab there as an export "Export HAR" button.  Thanks.

**Comment by balaG4046** [comment]
Hi @hubertdeng123  
We cant add the all ranges ip as internal ips which will be wide open to access our sentry server, kindly help us with any standard procedure fix in order to resolve the issue.

Thanks!
