### ISSUE TITLE
Database migration `IndexError: list index out of range` when upgrading to 25.6.1

### ISSUE THREAD

**Issue by JustScreaMy** [getsentry/self-hosted#3776]
### Self-Hosted Version

25.6.1

### CPU Architecture

x86_64

### Docker Version

28.2.2

### Docker Compose Version

v2.36.2

### Machine Specification

- [x] My system meets the minimum system requirements of Sentry

### Steps to Reproduce

1. Follow ugrade notes and try to upgrade from 25.5.1 to 25.6.1
2. Run `./install.sh`

### Expected Result

Upgrade finishes

### Actual Result
```
▶ Setting up / migrating database ...
 Container sentry-self-hosted-postgres-1  Creating
 Container sentry-self-hosted-postgres-1  Created
 Container sentry-self-hosted-postgres-1  Starting
 Container sentry-self-hosted-postgres-1  Started
 Container sentry-self-hosted-postgres-1  Waiting
 Container sentry-self-hosted-postgres-1  Healthy
 Container sentry-self-hosted-symbolicator-1  Creating
 Container sentry-self-hosted-smtp-1  Creating
 Container sentry-self-hosted-redis-1  Running
 Container sentry-self-hosted-postgres-1  Running
 Container sentry-self-hosted-kafka-1  Running
 Container sentry-self-hosted-clickhouse-1  Running
 Container sentry-self-hosted-snuba-api-1  Creating
 Container sentry-self-hosted-memcached-1  Creating
 Container sentry-self-hosted-smtp-1  Created
 Container sentry-self-hosted-memcached-1  Created
 Container sentry-self-hosted-symbolicator-1  Created
 Container sentry-self-hosted-snuba-api-1  Created
 Container sentry-self-hosted-symbolicator-1  Starting
 Container sentry-self-hosted-memcached-1  Starting
 Container sentry-self-hosted-smtp-1  Starting
 Container sentry-self-hosted-redis-1  Waiting
 Container sentry-self-hosted-clickhouse-1  Waiting
 Container sentry-self-hosted-kafka-1  Waiting
 Container sentry-self-hosted-symbolicator-1  Started
 Container sentry-self-hosted-smtp-1  Started
 Container sentry-self-hosted-memcached-1  Started
 Container sentry-self-hosted-redis-1  Healthy
 Container sentry-self-hosted-clickhouse-1  Healthy
 Container sentry-self-hosted-kafka-1  Healthy
 Container sentry-self-hosted-snuba-api-1  Starting
 Container sentry-self-hosted-snuba-api-1  Started
Updating certificates in /etc/ssl/certs...
0 added, 0 removed; done.
Running hooks in /etc/ca-certificates/update.d...
done.
sentry/requirements.txt is deprecated, use sentry/enhance-image.sh - see https://develop.sentry.dev/self-hosted/#enhance-sentry-image
Running migrations for default
Operations to perform:
  Apply all migrations: auth, contenttypes, explore, feedback, flags, hybridcloud, insights, monitors, nodestore, notifications, preprod, replays, sentry, sessions, sites, social_auth, tempest, uptime, workflow_engine
Running migrations:
  Applying sentry.0925_backfill_open_periods...Grouped Messages
05:47:18 [INFO] sentry.migrations.0925_backfill_open_periods: Processing batch for group open period backfill (last_group_id=3406918)
Traceback (most recent call last):
  File "/.venv/bin/sentry", line 4, in <module>
    raise SystemExit(main())
                     ~~~~^^
  File "/usr/src/sentry/src/sentry/runner/main.py", line 146, in main
    func(**kwargs)
    ~~~~^^^^^^^^^^
  File "/.venv/lib/python3.13/site-packages/click/core.py", line 1442, in __call__
    return self.main(*args, **kwargs)
           ~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "/.venv/lib/python3.13/site-packages/click/core.py", line 1363, in main
    rv = self.invoke(ctx)
  File "/.venv/lib/python3.13/site-packages/click/core.py", line 1830, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/.venv/lib/python3.13/site-packages/click/core.py", line 1226, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/.venv/lib/python3.13/site-packages/click/core.py", line 794, in invoke
    return callback(*args, **kwargs)
  File "/.venv/lib/python3.13/site-packages/click/decorators.py", line 34, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/src/sentry/src/sentry/runner/decorators.py", line 34, in inner
    return ctx.invoke(f, *args, **kwargs)
           ~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^
  File "/.venv/lib/python3.13/site-packages/click/core.py", line 794, in invoke
    return callback(*args, **kwargs)
  File "/usr/src/sentry/src/sentry/runner/commands/upgrade.py", line 157, in upgrade
    _upgrade(
    ~~~~~~~~^
        not noinput,
        ^^^^^^^^^^^^
    ...<5 lines>...
        create_kafka_topics,
        ^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/usr/src/sentry/src/sentry/runner/commands/upgrade.py", line 72, in _upgrade
    dj_call_command(
    ~~~~~~~~~~~~~~~^
        "migrate",
        ^^^^^^^^^^
    ...<3 lines>...
        verbosity=verbosity,
        ^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/.venv/lib/python3.13/site-packages/django/core/management/__init__.py", line 194, in call_command
    return command.execute(*args, **defaults)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^
  File "/.venv/lib/python3.13/site-packages/django/core/management/base.py", line 460, in execute
    output = self.handle(*args, **options)
  File "/.venv/lib/python3.13/site-packages/django/core/management/base.py", line 107, in wrapper
    res = handle_func(*args, **kwargs)
  File "/.venv/lib/python3.13/site-packages/django/core/management/commands/migrate.py", line 353, in handle
    post_migrate_state = executor.migrate(
        targets,
    ...<3 lines>...
        fake_initial=fake_initial,
    )
  File "/.venv/lib/python3.13/site-packages/django/db/migrations/executor.py", line 135, in migrate
    state = self._migrate_all_forwards(
        state, plan, full_plan, fake=fake, fake_initial=fake_initial
    )
  File "/.venv/lib/python3.13/site-packages/django/db/migrations/executor.py", line 167, in _migrate_all_forwards
    state = self.apply_migration(
        state, migration, fake=fake, fake_initial=fake_initial
    )
  File "/usr/src/sentry/src/sentry/new_migrations/monkey/executor.py", line 154, in apply_migration
    return super().apply_migration(state, migration, fake=fake, fake_initial=fake_initial)
           ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/.venv/lib/python3.13/site-packages/django/db/migrations/executor.py", line 255, in apply_migration
    state = migration.apply(state, schema_editor)
  File "/usr/src/sentry/src/sentry/new_migrations/migrations.py", line 28, in apply
    return super().apply(project_state, schema_editor, collect_sql)
           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/.venv/lib/python3.13/site-packages/django/db/migrations/migration.py", line 132, in apply
    operation.database_forwards(
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        self.app_label, schema_editor, old_state, project_state
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/.venv/lib/python3.13/site-packages/django/db/migrations/operations/special.py", line 196, in database_forwards
    self.code(from_state.apps, schema_editor)
    ~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/sentry/src/sentry/migrations/0925_backfill_open_periods.py", line 197, in backfill_group_open_periods
    _backfill_group_open_periods(apps, group_data)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
  File "/usr/src/sentry/src/sentry/migrations/0925_backfill_open_periods.py", line 156, in _backfill_group_open_periods
    get_open_periods_for_group(
    ~~~~~~~~~~~~~~~~~~~~~~~~~~^
        apps,
        ^^^^^
    ...<5 lines>...
        GroupOpenPeriod,
        ^^^^^^^^^^^^^^^^
    )
    ^
  File "/usr/src/sentry/src/sentry/migrations/0925_backfill_open_periods.py", line 73, in get_open_periods_for_group
    while activities and activities[start_index].type not in RESOLVED_ACTIVITY_TYPES:
                         ~~~~~~~~~~^^^^^^^^^^^^^
IndexError: list index out of range

Error in install/set-up-and-migrate-database.sh:22.
'$dcr web upgrade --create-kafka-topics' exited with status 1
-> ./install.sh:main:42
--> install/set-up-and-migrate-database.sh:source:22

Cleaning up...
```

**Comment by cuchac** [comment]
I've fixed this migration by changing line https://github.com/getsentry/sentry/blob/master/src/sentry/migrations/0925_backfill_open_periods.py#L73 to
`while start_index in activities and activities[start_index].type not in RESOLVED_ACTIVITY_TYPES:`

**Comment by aamarques** [comment]
I managed to resolve this issue by updating to version 2.6.0, applying the fix (below), and rerunning the install.sh script. Then, upgrading to version 2.6.1.

```
docker compose exec postgres bash
su postgres
psql

alter table sentry_groupsearchview alter user_id drop not null;
alter table sentry_groupsearchview alter organization_id drop not null;
```

Seems that this issue wasn't fixed by version 2.6.1 (#3774)  ([Release info](https://github.com/getsentry/self-hosted/releases/tag/25.6.1))
